### ISSUE TITLE
Latest release appears "unsigned"

### ISSUE THREAD

**Issue by ag14spirit** [tailscale/tailscale-qpkg#103]
QTS 5.1.0.2418 (build 2023-06-03) on QNAP TS-932PX

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale-qpkg/issues/99. We expect to correct this in the 1.42 release.

**Comment by ag14spirit** [comment]
I'm so sorry 🤦🏼‍♂️

I swear I checked...but clearly not very well.

**Comment by marcozink** [comment]
> Duplicate of #99. We expect to correct this in the 1.42 release.

You mean 1.43, or will you re-release a signed 1.42?
