### ISSUE TITLE
1.46.0 Release

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale-qpkg#107]
Hi Tailscale Team,

When will 1.46.0 be release as a qpkg? I noticed that we missed 1.44.2.

Thank you!

**Comment by d5aqoep** [comment]
It's already at 1.46.1

Why are they neglecting QNAP devices after ceremoniously appearing on it's native app store?

**Comment by jankatins** [comment]
My (complete outsider) bet: because it takes time to get releases approved by qnap before they appear in the qnap store?

**Comment by bradfitz** [comment]
That, and also not all patch releases apply to all platforms.

**Comment by d5aqoep** [comment]
They could at-least post latest builds without digital signature here. So people can still install them manually at periodic intervals.

**Comment by wingcomm** [comment]
> That, and also not all patch releases apply to all platforms.

@bradfitz I'm puzzled, we get fresh builds on every release on Synology on pkgs.tailscale.com. 1.44 has a lot of new features and the tailscale Admin GUI tells us that we should upgrade our QNAPs.

**Comment by cromelex** [comment]
Would be good to get the builds even if not signed, agreed.

**Comment by d5aqoep** [comment]
Thank you Tailscale guys. Latest signed version installed manually. It's still not available on QNAP App store yet. Maybe it would be available any moment soon.

**Comment by wingcomm** [comment]
Hi @DentonGentry Where is the QNAP x86_64 release for Tailscale 1.46.1? It seems to be missing...

**Comment by DentonGentry** [comment]
[The page of all releases](https://github.com/tailscale/tailscale-qpkg/releases) only shows 10 artifacts per release, you'd need to click on "show all 16 assets."

https://github.com/tailscale/tailscale-qpkg/releases/tag/v1.46.1 shows all of them without truncation.
