### ISSUE TITLE
1.48.2 digital signature invalid

### ISSUE THREAD

**Issue by marcozink** [tailscale/tailscale-qpkg#116]
Hello Team,

Seems that the latest package was not properly signed. This has happened before. Is there a way you can set the actions necessary to sign the package when a tag is released?

Thanks

**Comment by awly** [comment]
@marcozink what kind of package is it? Deb/rpm/something else?

**Comment by marcozink** [comment]
@awly In this case it's a qpkg since this repo is just for QNAP QTS

**Comment by binnychan** [comment]
Hi,

I am on QNAP TS-664 - QTS 5.1.1.2491 (2023/08/15) and use below qpkg.
https://github.com/tailscale/tailscale-qpkg/releases/download/v1.48.2/Tailscale_1.48.2-1_x86.qpkg

Below is the error on "Event Log"
Error	2023-09-13	10:27:22	---	---	Web Desktop	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.76	App Center	App Installation	[App Center] Failed to install Tailscale. The digital signature is invalid. To proceed with installation, go to App Center > Settings > General, and then select "Allow installation of applications without a valid digital signature".

**Comment by DocEmmetBrown** [comment]
I see the same thing with the [Tailscale_1.48.2-1_x86_64.qpkg](https://github.com/tailscale/tailscale-qpkg/releases/download/v1.48.2/Tailscale_1.48.2-1_x86_64.qpkg) package.

**Comment by DentonGentry** [comment]
The QNAP release is still done manually, we have not yet implemented it in the autobuilder. The manual process has to be able to build unsigned binaries, to allow people outside of Tailscale to build, so missing a step will result in not signing the packages.

I've uploaded replacement 1.48.2 packages which are signed.

**Comment by marcozink** [comment]
Thank you @DentonGentry I can confirm the new release is properly signed and has been installed without issues,

Thanks for the effort.
