### ISSUE TITLE
Exit Node has stopped working on QNAP

### ISSUE THREAD

**Issue by d5aqoep** [tailscale/tailscale-qpkg#120]
I tried downgrading to 1.40 but Exit Node does not work on QNAP.

**Comment by bradfitz** [comment]
Stopped working when? When did it work? When did it stop working?

There's no information here with which anybody can help debug anything.

**Comment by d5aqoep** [comment]
When I select my QNAP as exit node from any different location or a different device, internet completely stops working.
For example, I use exit node to authenticate netflix on my iPhone when I am away from home. But now when I select QNAP as exit node on my iPhone, the interent just stops working. I tested this from another Windows 11 based PC too.

**Comment by DentonGentry** [comment]
We would need a bugreport, or some way to identify the tailnet in order to be able to work on this.
At this point I'd suggest filing this as a support ticket: https://tailscale.com/contact/support/
The support team can work with you via email.
