### ISSUE TITLE
Update Tailscale in QNAP official App Center

### ISSUE THREAD

**Issue by meyerjom** [tailscale/tailscale-qpkg#121]
Once you have migrated from the QPNG installation to the official App Store version, you get errors when migrating back. Therefore, the question:

Are there still updates in the QNAP Store for Tailscale? The version there is quite outdated. Thank you!

**Comment by DentonGentry** [comment]
The version in the QNAP App Center was released June 15: https://tailscale.com/changelog/#2023-06-15-service, 3 1/2 months ago.

Updating the QNAP App Center is an entirely manual process, for both Tailscale in the submission process and for QNAP in their test process. We release Tailscale updates monthly. In no Universe will QNAP run their test process every month. We are currently doing a significant amount of work on the web interface, used in QNAP/Synology/Unraid etc. When that work is complete we expect to submit updates to several store listings, those which require significant manual testing to release.

**Comment by curryhendry** [comment]
已经2年没有更新了，qnap上的版本是1.40.0，现在最新版本应该是1.80.2
