### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by dnerpzza** [tailscale/tailscale-qpkg#125]
_Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@NAS to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log._

****Im getting this Error if i try to start tailscale. I am really desperate for help. Can someone help?****

**Comment by DentonGentry** [comment]
This is the third issue you've opened in trying to get started using Tailscale. Please contact Tailscale support using the contact form at the bottom of: https://tailscale.com/contact/support/

We have an entire team able to help. Public bug reports are not working for this.
