### ISSUE TITLE
1.52.0 digital signature invalid

### ISSUE THREAD

**Issue by DocEmmetBrown** [tailscale/tailscale-qpkg#127]
Hey folks,
it looks like the latest release was not signed as it used to be.
I tried to install `Tailscale_1.52.0-1_x86_64.qpkg` , and I get the "digital signature invalid", just like in #116 

Thanks for your help

**Comment by DentonGentry** [comment]
Replaced with properly signed packages.

**Comment by DocEmmetBrown** [comment]
Thanks a ton @DentonGentry !
