### ISSUE TITLE
Add QNAP Package Builds to pkgs.tailscale.com

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale-qpkg#135]
Can we add QNAP packages to Tailscale's regular build processes so they get posted along with the Synology packages on  https://pkgs.tailscale.com/ ?

**Comment by d5aqoep** [comment]
Yeah, we don't care about digital signatures as long as they come from official tailscale website. The github builds are months outdated and it seems like hardly anyone bothers to update them.

**Comment by d5aqoep** [comment]
The current qnap version is very outdated. Do we have an approx ETA on latest version availability?

**Comment by bradfitz** [comment]
Work is actively underway, as you can see above.

**Comment by soniaappasamy** [comment]
Signed QNAP builds are now part of pkgs.tailscale.com: https://pkgs.tailscale.com/unstable/#qpkgs
