### ISSUE TITLE
Implement basic GUI for QTS

### ISSUE THREAD

**Issue by ivokub** [tailscale/tailscale-qpkg#16]

**Comment by ivokub** [comment]
It seems that 1.8 has now built-in web service for controlling Tailscale node. I would need to check if it is possible to have some kind of authentication so that this service could only be exposed to QNAP user.

**Comment by ivokub** [comment]
> It seems that 1.8 has now built-in web service for controlling Tailscale node. I would need to check if it is possible to have some kind of authentication so that this service could only be exposed to QNAP user.

I tried to integrate the Tailscale web interface with QTS and it is in general possible. However, it seems that `tailscale web` command itself is broken (see https://github.com/tailscale/tailscale/issues/1939).

We can also have authentication - assuming that QNAP proxies connections to Tailscale web UI and if Tailscale could detect that it is running inside QNAP (by adding a new variant in tailscale/versions), then it recover session cookie from the browser and validate it with `/home/httpd/cgi-bin/authLogin.cgi` using `QUERY_STRING="SID=XXX"` environment variable. This requires some additional implementation in Tailscale itself.

**Comment by DentonGentry** [comment]
Tailscale login has been implemented in a web ui, using `tailscale web -cgi`
