### ISSUE TITLE
Tailscale service runs for a while and then stops

### ISSUE THREAD

**Issue by russellhurren** [tailscale/tailscale-qpkg#49]
On my own QNAP NAS I'm using this package with version 1.22.0 with no issues at all.
One of my clients has 2 NASs using this package, one with version 1.22.0 and one with 1.24.2.
Both of the clients NASs will disconnect from Tailscale after a period of time. I asked the client to restart the app and it came back online and when I logged into the NAS and opened the Apps page, it disconnected. I'd like to update them but I don't have any access except via Tailscale.
Any advice on how to troubleshoot would be appreciated. I can go onsite if necessary, but I don't want to waste the client's time if I don't know what's wrong with it.

**Comment by scheini1972** [comment]
Did you disable key expiry on the admin console of tailscale?

**Comment by russellhurren** [comment]
It's disabled on mine but my client hadn't disabled it on his. Will get him to try that and see if it fixes the problem, thanks.

**Comment by ivokub** [comment]
Could you try running the Tailscale daemon manually? The current initialisation script redirects all output to /dev/null and any possible errors are discarded. For that, go to the Tailscale QPKG directory and run
```
/tailscaled --port 41641 --state=var/lib/tailscale/tailscaled.state --socket=var/run/tailscale/tailscaled.sock
```

**Comment by russellhurren** [comment]
Thanks. I asked the client to disable key expiry a few days ago and yesterday I was able to do a remote session and upgrade the Tailscale packages on the NASs. So far it's still working. If the problem comes back I'll give that a go and look for errors.

**Comment by DentonGentry** [comment]
I think this is resolved.
