### ISSUE TITLE
Latest Release?

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale-qpkg#52]
Any plans to release 1.32.3 for QNAP ? :)

**Comment by DentonGentry** [comment]
We checked in changes two hours ago preparing to release for the QNAP App Center. The timing of the App Center release isn't something we control.

**Comment by DentonGentry** [comment]
I'm trying to get the workflow to run to release a 1.32.3 package to https://github.com/tailscale/tailscale-qpkg/releases

Once we get the package into the App Center, which requires a different build process and a signing key, I'd expect to discontinue releases in https://github.com/tailscale/tailscale-qpkg/releases

**Comment by DentonGentry** [comment]
I created a 1.32.3 release and uploaded the artifacts.

**Comment by wingcomm** [comment]
@DentonGentry Any plans for 1.34.1?

**Comment by wingcomm** [comment]
@DentonGentry 1.36.0? :)
