### ISSUE TITLE
how to get https certificate in qnap?

### ISSUE THREAD

**Issue by lincolntan36** [tailscale/tailscale-qpkg#53]
Every time I try to get a certificate this happens:

 
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # `sudo ./tailscale cert qnap.tailnet-name.ts.net`
Failed to connect to local Tailscale daemon for /localapi/v0/cert/qnap.tailnet-name.ts.net; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

Even if i just type in `sudo ./tailscale` cert same error happens

**Comment by lincolntan36** [comment]
turns out all commands needed the `-socket` argument
`./tailscale -socket var/run/tailscale/tailscaled.sock`

**Comment by cyklee** [comment]
For those who care, the location of tailscaled.sock has now been changed (to the expected default `/tmp/tailscale/tailscaled.sock`) so you don't need to specify `--socket` and just use: `./tailscale cert`.
