### ISSUE TITLE
No login on QTS

### ISSUE THREAD

**Issue by GoetzGoerisch** [tailscale/tailscale-qpkg#54]
I was using the QnapClub Pkg before.

Now I removed this and installed the latest version from here. 
Installing works, but it does not proceed to a login page nor does it place a textfile, like the other package in Public, with the login link.

Firmware: QTS 5.0.1.2194
Platform: x86_64

**Comment by GoetzGoerisch** [comment]
Additional info:

I verified that the tailscale is running. But I see no webui path configured in the app config.

```
[Tailscale]
Status = complete
Name = Tailscale
Build = 20221123
Display_Name = Tailscale
Version = v1.32.3
Author = root
QPKG_File = Tailscale.qpkg
Date = 2022-11-25
Shell = /share/CE_CACHEDEV1_DATA/.qpkg/Tailscale/Tailscale.sh
Install_Path = /share/CE_CACHEDEV1_DATA/.qpkg/Tailscale
RC_Number = 101
FW_Ver_Min = 4.1.0
Enable = TRUE
```

Also no icon is shown in app center:
![image](https://user-images.githubusercontent.com/47734341/203925281-bf2e7007-dc8c-4607-a5ff-01830d01e3bc.png)

**Comment by DentonGentry** [comment]
```
Build = 20221123
FW_Ver_Min = 4.1.0
```

This looks like the package from https://github.com/tailscale/tailscale-qpkg/releases/tag/v1.32.3, is that correct? That package is supposed to be exactly like the previous versions, with the only change being to update to 1.32.3. It expects to be started using `tailscale up` from an SSH session.

The code in the tree is preparing for an App Center release, with graphical login and a signed package. We're still going through QNAP's Developer process to get it released.

**Comment by GoetzGoerisch** [comment]
Thx @DentonGentry! I was fooled by the readme of the `main` branch and thought the 1.32.3 release is already working like described there.

That's why I was running QnapClub pkg before, as the login process did not require SSH access.

Looking forward to see the pkg in Qnap Store.
