### ISSUE TITLE
QPKG installs but does not open

### ISSUE THREAD

**Issue by nbarari** [tailscale/tailscale-qpkg#56]
Firmware Version: 4.3.4.2107 Build 20220712
Tailscale Version: v1.32.3

I have attempted to install the precompiled Tailscale_v1.32.3_x86.qpkg & Tailscale_v1.32.3_x86_64.qpkg files, and while they install successfully and start, selecting open does not do anything. I attempted to SSH in and run `sudo qpkg_service start tailscale`, and the command appears to start the service, however nothing else happens and I am not presented with the auth URL. QVPN Service has already been installed, but no VPN services have been configured.

How can I proceed?

**Comment by DentonGentry** [comment]
`main` holds the current development intended for the QNAP APP Center. The 1.32.3 release available for download was built using the existing implementation updated for 1.32.3. The README for how to enable it is on the `update` branch: https://github.com/tailscale/tailscale-qpkg/tree/update

**Comment by nbarari** [comment]
That worked, appreciate the help!
