### ISSUE TITLE
tailscaled log cause RAMdisk full

### ISSUE THREAD

**Issue by Bpazy** [tailscale/tailscale-qpkg#57]
I found out that QNAP root filesystem full becase tailscaled write logs into `/var/lib/tailscale` continuously. Full RootFS makes QNAP not working.

QNAP root filesystem is `400M` RAMdisk and released only restarting:
```sh
[/var/lib/tailscale] # df -h
Filesystem                Size      Used Available Use% Mounted on
none                    400.0M    310.9M     89.1M  78% /
```
In my QNAP, `tailscaled.log1.txt` take up `30M`. Unfortunately, I delete it and forgoting to back up the log.

Here's grafana monitor shows increased disk usage:
![image](https://user-images.githubusercontent.com/9838749/204753903-6ecff198-2ad6-4845-b309-925c359e867f.png)
And resloved after deleting tailscale and log:
![image](https://user-images.githubusercontent.com/9838749/204802669-1e8ca6b8-24c7-46dd-957c-5bb2e86b35da.png)

Maybe logs should be disabled or cleanup regularly.

**Comment by DentonGentry** [comment]
Could I ask what version of the package you are running? https://github.com/tailscale/tailscale/pull/5163/files was supposed to move the logs to /tmp/tailscale-logs and limit their max size to 1 Megabyte, and went into 1.30.x.

**Comment by Bpazy** [comment]
@DentonGentry thank you. i'm not sure about the exact version but it should be a very old version in 2021. 

i will try latest version to checkout

**Comment by Bpazy** [comment]
not reproduce at latest tailscale. I will close the issue.
