### ISSUE TITLE
Qnap App Center ?

### ISSUE THREAD

**Issue by DocEmmetBrown** [tailscale/tailscale-qpkg#59]
Hey Folks, 
my understanding from #52 was that this package was gonna be ported to the "official" Qnap App center, but I can't manage to find it ? 
Is this still WIP ? and if yes, would you be a able to release the new versions in that repo ? 
Thanks a lot

**Comment by DentonGentry** [comment]
I promise that we will update the description when the situation with the App Center changes.
We've uploaded 1.34.1 qpkgs to this repo.
