### ISSUE TITLE
Tailscale post-install setup requires a valid NAS SSL cert

### ISSUE THREAD

**Issue by chder** [tailscale/tailscale-qpkg#62]
I decided to try out the new QNAP package on:
https://github.com/tailscale/tailscale-qpkg/releases/download/qnap-v1.34.1/Tailscale_1.34.1-1_arm-x41.qpkg

After install, clicking on the Tailscale app to set it up fails with an SSL error in the body of the page that opened.

```
Get "https://nas.internal/cgi-bin/authLogin.cgi?sid=mfe72ex6": x509: certificate is not valid for any names, but wanted to match nas.internal
```

The install docs should mention a valid SSL cert is required and/or suggest how to do it from the CLI manually... which is what I ended up doing to workaround that with `/share/CACHEDEV1_DATA/.qpkg/Tailscale/tailscale up`

After I got Tailscale up and I changed QNAP to not force HTTPS logins to test this out, I was able to log in via HTTP:// on the Tailscale interface IP address and the Tailscale web UI loaded.

QTS 5.0.1.2248
TS version 1.34.1-1

**Comment by DentonGentry** [comment]
The actual release is https://github.com/tailscale/tailscale-qpkg/releases/tag/v1.34.1, please use that one.

**Comment by chder** [comment]
I did try that release at one point but got confused since "Open" didn't do anything and I had already seen the pre-released version did... but now I notice it's because I should have followed the setup instructions from that release's [README.md](https://github.com/tailscale/tailscale-qpkg/blob/v1.34.1/README.md#installation).
