### ISSUE TITLE
Build fails with build.tailscale.io not found

### ISSUE THREAD

**Issue by 17castlest** [tailscale/tailscale-qpkg#68]
Hi

After downloading and unzipping tailscale-qpkg-main.zip, I run make pkg. This creates the directory out/tailscale-1.34.2 places 8 executable files into that directory: tailscale-386, tailscale-amd64, etc.

The build then fails with the following message:

docker run --rm \
	-e TSTAG=1.34.2 \
	-e QNAPTAG=1 \
	-v /home/alistair/tailscale-qpkg-main/out/tailscale-1.34.2:/out \
	-v /home/alistair/tailscale-qpkg-main/Tailscale:/Tailscale \
	-v /home/alistair/tailscale-qpkg-main/build/build-qpkg.sh:/build-qpkg.sh \
	build.tailscale.io/qdk:latest \
	/build-qpkg.sh
Unable to find image 'build.tailscale.io/qdk:latest' locally
docker: Error response from daemon: Get "https://build.tailscale.io/v2/": dial tcp: lookup build.tailscale.io: no such host.

As far as I can tell, build.tailscale.io does not exist. Am I missing something?

Alistair

**Comment by DentonGentry** [comment]
Could you `make build-qdk-container` first and then `make pkg`? I think we're missing a step in the documentation.

We should probably also rename the container, build.tailscale.io is misleading.

**Comment by 17castlest** [comment]
That worked, thanks.
