### ISSUE TITLE
1.36.x won't install on QNAP 4.5.2

### ISSUE THREAD

**Issue by jdtate101** [tailscale/tailscale-qpkg#79]
I have a TS-453A running code 4.5.2.1566 . This is quite old as when I last tried to upgrade to QNAP 5.x it bricked my NAS and I had to do a recovery boot and reload. I'm hesitant to upgrade as the NAS is rock solid right now. The latest version of tailscale fails on install with the warning QNAP code 5.x is needed. Is there any way around this. It's working just fine with 1.34.1...but keeping it up to date would be nice.

**Comment by DentonGentry** [comment]
We tried, by purchasing a refurbished TS-231K which arrived with QTS 4.x. Without us ever telling it to do so, it updated itself to QTS5 overnight one night. QNAP is apparently pushing to get devices onto QTS5.

At this point I don't expect to be able to support QTS4. We do not have a way to develop for it nor test it.

**Comment by jdtate101** [comment]
I should hopefully be ok leaving it on 1.34.1 until tailscale breaks that functionality...hopefully not for a long time, otherwise I'll have to investigate alternatives. I will probably replace the NAS in the next yr so that would also solve the issue. Thx for the reply.
