### ISSUE TITLE
QNAP Tailscale leaking traffic to its default route

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale-qpkg#81]
I'm getting flurries of alerts from my IPS that my QNAP (and only my QNAP) is trying to route traffic from its LAN address on my network to its Tailscale (100.64.0.0/10) address through my router rather than encapsulating it into the tailscale mesh network.

Anyone else seeing this?

**Comment by bradfitz** [comment]
Without any sort of "tailscale bugreport" or Tailscale IP or details we'll probably be unable to help. I suspect it's not configured as you assume it is.

**Comment by wingcomm** [comment]
Tailscale 1.36.1 does not work on QTS 5.x. I'll open a new bug.
