### ISSUE TITLE
expose subnet?

### ISSUE THREAD

**Issue by cb2206** [tailscale/tailscale-qpkg#89]
I'm new to qnap and tailscale. So, please bear with me. :-)
I was able to build the qpkg, install it and connect the tailscale instance on qnap. But I would like to expose a subnet from qnap. On a macOS machine, I was able to do that via "tailscale up --advertise-routes=192.x.x.x/24" but I'm unclear how to get that done for the tailscale install on qnap. 
Any pointers? Thanks a lot for this qpkg builder and your responses!

**Comment by DentonGentry** [comment]
Advertising subnet routes isn't a supported feature for QNAP platforms, if you want to enable it you'll need to use the CLI:
/share/CACHEDEV1_DATA/.qpkg/Tailscale/tailscale up --advertise-routes=192.x.x.x/24

**Comment by cb2206** [comment]
Awesome, thanks a lot @DentonGentry
