### ISSUE TITLE
Now to update tailscale-qpkg - from 1.36.1 to 1.38.3?

### ISSUE THREAD

**Issue by Aldenhamian** [tailscale/tailscale-qpkg#90]
The latest release here is 1.36.1 and there hasn't been any updates since.
https://github.com/tailscale/tailscale-qpkg/releases

How do I update to the latest Tailscale release version 1.38.3?

**Comment by DentonGentry** [comment]
We are working with QNAP on testing of the 1.36 release to make available through QNAP's app center. I don't expect to update the client version until that is complete.

Clients on other platforms using 1.38.3 remain compatible with a 1.36.x release on other devices.

**Comment by Aldenhamian** [comment]
Great!  Thank you for all the good work!
