### ISSUE TITLE
Tailscale appliation not starting when qnap server is restart

### ISSUE THREAD

**Issue by athinaok** [tailscale/tailscale-qpkg#94]
Hello
When I restart Qnap server (TS231P ) application is started but it is not in reality. I must Stop the application and start it. Then it will work with no problems.
Thank you

**Comment by DentonGentry** [comment]
That should be fixed by https://github.com/tailscale/tailscale-qpkg/pull/93 which will be in the next release we post, expected to be 1.40.0.

**Comment by DentonGentry** [comment]
Fixed in 1.40.0.

**Comment by DroppedLink** [comment]
Im running on a TS-231K and the above seems to exist on this device 
Running Tailscale 1.40.1.0

(Stop and restart and it's then working. 

P.S. Thanks for all you do!
