### ISSUE TITLE
XML syntax error on line 16: invalid character entity & (no semicolon)

### ISSUE THREAD

**Issue by RJDavison** [tailscale/tailscale-qpkg#97]
v1.40 gives me this error when opening Tailscale.

QTS 5.1 on a TS-264

**Comment by malbert911** [comment]
How did you fix this? @RJDavison 

I am getting `XML syntax error on line 22: element <link> closed by </head>` on a blank white page at URI `/cgi-bin/qpkg/Tailscale/index.cgi` when accessing Tailscale 1.40 on a TS-230

**Comment by RJDavison** [comment]
Are you logging into the nas through something like cloudflared tunnels? I
was and found that if I ran tailscale from the same network as the NAS then
it all worked.
