### ISSUE TITLE
Tailscale_1.42.0-1_x86_64.qpkg - The digital signature is invalid.

### ISSUE THREAD

**Issue by KilllerRabbbit** [tailscale/tailscale-qpkg#99]
[App Center] Failed to install Tailscale. The digital signature is invalid. To proceed with installation, go to App Center > Settings > General, and then select "Allow installation of applications without a valid digital signature".

The previous release is installing without such problems.

**Comment by johntait** [comment]
Same here. I was able to upgrade from 1.40.0 by allowing applications without a valid digital signature and when I look in the app center Tailscale 1.42.0 shows as not having a digital signature.

**Comment by delaveganz** [comment]
Ditto here. Previous versions did not have a signature issue. Hope this can be resolved.

**Comment by KilllerRabbbit** [comment]
Do you plan to publish properly signed build? That shouldn't be a big problem once you succeeded with previous builds.

**Comment by marcozink** [comment]
New version has been released, 1.46.1, now signed.

I think we can close this issue now
